InferenceEngineClient initialized with 2 engines.
Total steps: 2350
Validation set size: 3
Validation set size: 1
Generating train split: 115 examples [00:00, 8387.88 examples/s]
2025-08-06 18:25:37.752 | INFO     | skyrl_train.dataset.dataset:_read_files_and_tokenize:39 - dataset len: 115
Filtering prompts longer than 16384 tokens (num_proc=8): 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 115/115 [00:02<00:00, 46.85 examples/s]
2025-08-06 18:25:40.400 | INFO     | skyrl_train.dataset.dataset:_read_files_and_tokenize:51 - filter dataset len: 115
2025-08-06 18:25:40.401 | INFO     | skyrl_train.entrypoints.main_base:get_test_datasets:201 - Loaded test dataset 'retail' from data/tau_bench_test/retail_test.parquet
Generating train split: 50 examples [00:00, 6562.01 examples/s]
2025-08-06 18:25:40.468 | INFO     | skyrl_train.dataset.dataset:_read_files_and_tokenize:39 - dataset len: 50
Filtering prompts longer than 16384 tokens (num_proc=8): 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 50/50 [00:02<00:00, 19.24 examples/s]
2025-08-06 18:25:43.274 | INFO     | skyrl_train.dataset.dataset:_read_files_and_tokenize:51 - filter dataset len: 50
2025-08-06 18:25:43.274 | INFO     | skyrl_train.entrypoints.main_base:get_test_datasets:201 - Loaded test dataset 'airline' from data/tau_bench_test/airline_test.parquet
Validation set size: 1
2025-08-06 18:25:43.275 | INFO     | skyrl_train.trainer:set_test_datasets:147 - Added test dataset 'retail' with 115 examples
Validation set size: 1
2025-08-06 18:25:43.276 | INFO     | skyrl_train.trainer:set_test_datasets:147 - Added test dataset 'airline' with 50 examples
2025-08-06 18:25:50.492 | INFO     | skyrl_train.workers.worker:_initiate_actors:543 - Initializing process group for RayActorGroup
2025-08-06 18:25:58.505 | INFO     | skyrl_train.workers.worker:_initiate_actors:545 - Initialized process group for RayActorGroup
2025-08-06 18:25:58.522 | INFO     | skyrl_train.workers.worker:_initiate_actors:547 - Mesh Ranks: [MeshRank(dp=0, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=1, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=2, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=3, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=4, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=5, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=6, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=7, sp=0, tp=0, world_size=8, dp_size=8)]
2025-08-06 18:26:05.477 | INFO     | skyrl_train.workers.worker:_initiate_actors:543 - Initializing process group for RayActorGroup
2025-08-06 18:26:13.420 | INFO     | skyrl_train.workers.worker:_initiate_actors:545 - Initialized process group for RayActorGroup
2025-08-06 18:26:13.437 | INFO     | skyrl_train.workers.worker:_initiate_actors:547 - Mesh Ranks: [MeshRank(dp=0, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=1, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=2, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=3, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=4, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=5, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=6, sp=0, tp=0, world_size=8, dp_size=8), MeshRank(dp=7, sp=0, tp=0, world_size=8, dp_size=8)]
Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): [36mray::FSDPRefRayActorBase.init_model()[39m (pid=1863563, ip=240.20.60.106, actor_id=17cf76c99dcc503a4950fd4801000000, repr=<skyrl_train.workers.fsdp.fsdp_worker.FSDPRefRayActorBase object at 0x7ed79e3407a0>)
  File "/root/miniconda3/envs/ctu/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/ctu/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
           ^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/CTU-Agent-v0/SkyRL_mod/skyrl-train/skyrl_train/workers/fsdp/fsdp_worker.py", line 371, in init_model
    model = Actor(
            ^^^^^^
  File "/root/CTU-Agent-v0/SkyRL_mod/skyrl-train/skyrl_train/models.py", line 72, in __init__
    assert self.use_flash_attention_2, "Flash attention 2 should be used for `use_sample_packing`"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Flash attention 2 should be used for `use_sample_packing`
